apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.containerPort }}
      protocol: TCP
      targetPort: {{ .Values.containerPort }}
    - port: {{ .Values.managementPort }}
      protocol: TCP
      targetPort: {{ .Values.managementPort }}
  selector:
    app: {{ .Release.Name }}