apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: api-specification-template
  title: OpenAPI Specification
  description: Create an OpenAPI specification
spec:
  owner: service@example.com
  type: api
  
  parameters:
    - title: API server parameters
      required:
        - api_id
        - owner
        - application
        - description
      properties:
        api_id:
          title: Name
          type: string
          description: Unique name of the API
        description:
          title: Description
          type: string
          description: Help others understand what this website is for.
        owner:
          title: Owner
          type: string
          description: Owner of the API
          ui:field: OwnerPicker
          ui:options:
            allowedKinds: 
              - Group
        application:
          title: System
          type: string
          description: System to which this API belongs
          ui:field: OwnedEntityPicker
          ui:options:
            allowedKinds:
            - System       
    - title: Choose a location  
      required:
        - repoUrl
      properties: 
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
            allowedOwners:
              - janus-api-idp  

  steps:
    - id: template
      name: Code Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        copyWithoutRender: []
        values:
          api_id: ${{ parameters.api_id }}
          description: ${{ parameters.description }}
          artifact_id: ${{ parameters.api_id }}
          java_package_name: ${{ parameters.java_package_name }}
          owner: ${{ parameters.owner }}
          destination: ${{ parameters.repoUrl | parseRepoUrl }}
          http_port: 8080
          application: ${{ parameters.application }}
          

    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: This is ${{ parameters.api_id }}
        repoUrl: ${{ parameters.repoUrl }}
        repoVisibility: public
        deleteBranchOnMerge: true
        access: janus-api-idp/${{ parameters.owner }}
        protectDefaultBranch: false        

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: '${{ steps.publish.output.repoContentsUrl }}'
        catalogInfoPath: '/catalog-info.yaml'

    - id: template-tenant-gitops 
      name: tenant Argcd Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./app-gitops
        copyWithoutRender: []
        values:
          api_id: ${{ parameters.api_id }}
          description: ${{ parameters.description }}
          artifact_id: ${{ parameters.api_id }}
          java_package_name: ${{ parameters.java_package_name }}
          owner: ${{ parameters.owner }}
          application: ${{ parameters.application }}
          organization: janus-api-idp
          team: ${{ parameters.owner }}
          repo_id: ${{ parameters.api_id }}
        targetPath: ./tenant-gitops          

    - id: pull-request
      name: make a pr with the new argocd
      action: publish:github:pull-request
      input:
        repoUrl: github.com?repo=${{ parameters.application.split(":")[1] }}-gitops&owner=janus-api-idp
        branchName: ${{ parameters.api_id }}
        title: argocd apps for ${{ parameters.api_id }}
        description: argocd apps ${{ parameters.api_id }}
        sourcePath: ./tenant-gitops  

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
