apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{ values.component_id }}-pipeline
  namespace: ${{values.application.split(":")[1]}}-build
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/janus-api-idp/${{ values.component_id }}
    targetRevision: HEAD
    path: .tekton
    helm:
      values: | 
        image: 
          tag: latest
  destination:
    server: https://kubernetes.default.svc
    namespace: ${{values.application.split(":")[1]}}-build
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 10m