apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ${{values.api_id | dump}}
  title: ${{values.api_id | dump}}
  description: ${{values.description | dump}}
spec:
  type: openapi
  system: ${{values.application}}
  owner: ${{values.owner | dump}}
  lifecycle: experimental
  definition:
    $openapi: ${{ values.destination | dump }}/blob/main/specification.yaml