openapi: 3.0.3
info:
  title: ${{ values.api_id }}
  description: |-
    ${{ values.description }}
  version: 0.0.1
servers:
  - url: "http://localhost:8080"
  - url: "https://microcks-microcks.apps.cluster-65qcl.dynamic.redhatworkshops.io/rest/${{ values.api_id }}/0.0.1"
paths: {}