openapi: 3.0.3
info:
  title: ${{ values.api_id }}
  description: |-
    ${{ values.description }}
  version: 0.0.1
servers:
  - url: "https://microcks-microcks.apps.cluster-8dcp2.dynamic.opentlc.com/rest/${{ values.api_id }}/0.0.1"
paths: {}