apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: api-specification-template
  title: OpenAPI Specification
  description: Create an OpenAPI specification
spec:
  owner: service@example.com
  type: api
  
  parameters:
    - title: API server parameters
      required:
        - api_id
        - owner
        - application
        - description
      properties:
        api_id:
          title: Name
          type: string
          description: Unique name of the API
        description:
          title: Description
          type: string
          description: API description
        owner:
          title: Owner
          type: string
          description: Owner of the API
          ui:field: OwnerPicker
          ui:options:
            allowedKinds: 
              - Group
        application:
          title: System
          type: string
          description: System to which this API belongs
          ui:field: OwnedEntityPicker
          ui:options:
            allowedKinds:
            - System       
    - title: Choose a location  
      required:
        - repoUrl
      properties: 
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
            allowedOwners:
              - janus-api-idp  

  steps:
    - id: template
      name: Code Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        copyWithoutRender: []
        values:
          api_id: ${{ parameters.api_id }}
          description: ${{ parameters.description }}
          artifact_id: ${{ parameters.api_id }}
          owner: ${{ parameters.owner }}
          destination: ${{ parameters.repoUrl | parseRepoUrl }}
          http_port: 8080
          application: ${{ parameters.application }}

    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: This is ${{ parameters.api_id }}
        repoUrl: ${{ parameters.repoUrl }}
        repoVisibility: public
        deleteBranchOnMerge: true
        #access: janus-api-idp/${{ parameters.owner }}
        protectDefaultBranch: false        
