apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.component_id }}
  description: ${{values.description}}
  annotations:
    argocd/app-name: ${{values.namespace}}
    backstage.io/kubernetes-id: ${{values.component_id}}
    backstage.io/kubernetes-namespace: ${{values.namespace}}
    tektonci/build-namespace: ${{ values.namespace }}
    #backstage.io/techdocs-ref: url:https://${{values.git_host}}/${{values.git_group}}/${{values.component_id}}
    backstage.io/source-location: url:https://${{values.git_host}}/${{values.git_group}}/${{values.component_id}}
    janus-idp.io/tekton:  ${{values.component_id}}
    gitlab.com/project-slug: ${{values.git_group}}/${{values.component_id}}
    quay.io/repository-slug: ${{values.image_host}}/${{values.namespace}}/${{values.component_id}}
  tags:
    - java
    - camel
    - jdbc
  links:
    - url: https://console-openshift-console${{values.cluster_id}}/dev-pipelines/ns/${{values.namespace}}/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console${{values.cluster_id}}/k8s/ns/${{values.namespace}}/deployments/${{values.component_id}}
      title: Deployment
      icon: web
    - url: https://devspaces${{values.cluster_id}}/#https://${{values.git_host}}/${{values.git_group}}/${{values.component_id}}?che-editor=che-incubator/che-code/latest&devfilePath=.devfile.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: https://hawtio-online-hawtio.apps.cluster-xcbw9.sandbox2706.opentlc.com/online
      title: HawtIO Online
      icon: web # it would be nice to have an hawtio icon
spec:
  type: service
  lifecycle: experimental
  owner: ${{values.owner | dump}}
  system: camel-jdbc-system-${{values.component_id}}
  providesApis: 
    - ${{values.component_id}}
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: camel-jdbc-system-${{values.component_id}}
  tags:
    - backstage
spec:
  owner: ${{ values.owner | dump }}
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ${{values.component_id}}
  description: API exposed by TODO App
  links:
    - url: http://${{values.component_id}}-${{values.namespace}}${{values.cluster_id}}/api-doc
      title: API Spec
      icon: code
spec:
  type: openapi
  lifecycle: production
  owner: ${{values.owner | dump}}
  system: camel-jdbc-system-${{values.component_id}}
  definition:
    $text: https://${{values.git_host}}/${{values.git_group}}/${{values.component_id}}/-/blob/main/src/main/resources/${{values.openapi_name}}
