- route:
    id: router-timer-to-log
    nodePrefixId: route-timer-to-log
    from:
      id: from-timer-to-log
      uri: timer
      parameters:
        timerName: from-yaml
        period: "{{timer.period}}"
      steps:
        - to:
            id: timer-to-log-http
            uri: https
            parameters:
              httpUri: https://api.chucknorris.io/jokes/random
        - setBody:
            id: timer-to-log-setBody
            expression:
              jsonpath:
                id: timer-to-log-jsonPath
                expression: $.value
        - to:
            id: log-timer-to-log
            uri: log
            parameters:
              loggerName: timer-yaml